'use strict';
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const {loadConfig,validateConfig,browserSource}=require('../scripts/config.cjs');
const data=loadConfig(),world=vm.createContext({});vm.runInContext(browserSource(data),world);
assert.deepEqual(JSON.parse(JSON.stringify(world.ZERO_CONFIG)),JSON.parse(JSON.stringify(data)));
assert.ok(Object.isFrozen(data.weapons.smg));
const invalid=edit=>{const d=JSON.parse(JSON.stringify(data));delete d.hash;edit(d);assert.throws(()=>validateConfig(d));};
invalid(d=>delete d.heroes.vanguard.maxHp);
invalid(d=>d.weapons.smg.interval=0);
invalid(d=>d.weapons.smg.unexpected=1);
invalid(d=>d.heroes.vanguard.weapon='missing');
invalid(d=>d.progression.combatCrateChance=1.1);
invalid(d=>d.chips.push(d.chips[0]));
invalid(d=>d.synergies[0].need=['missing']);
invalid(d=>d.zones[0].maps=['missing']);
invalid(d=>d.enemies.boss.pools[1]=['missing']);
const adjusted=JSON.parse(JSON.stringify(data));
adjusted.chips.reverse();adjusted.chips.find(c=>c.id==='overcharge').params.damage=0.5;
const effectWorld=vm.createContext({ZERO_CONFIG:adjusted});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../src/core.js'),'utf8'),effectWorld);
const stats={dmg:1};effectWorld.ZERO_CORE.CHIPS.find(c=>c.id==='overcharge').apply(stats,2);
assert.equal(stats.dmg,2,'Effects bind named parameters by ID even after reordering');
const {createGame}=require('../src/game.js');require('../src/core.js');
const G=createGame({seed:1,headless:true});G.startRun();G.bossTuning={hpMul:0.9};
const snapshot=G.getConfiguration();G.bossTuning.hpMul=0.5;
assert.equal(snapshot.overrides.bossTuning.hpMul,0.9,'Report overrides are copied');
assert.equal(snapshot.hash,data.hash);
console.log('PASS: JSON/Node/browser parity, freeze, nine invalid configurations, ID-bound tuning and report snapshots.');
